version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: suite-mongodb-dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - "27017:27017"
    volumes:
      - mongodata-dev:/data/db
    restart: always

  redis:
    image: redis:7-alpine
    container_name: suite-redis-dev
    ports:
      - "6379:6379"
    restart: always

volumes:
  mongodata-dev:
